apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tap-jenkins-app-workload
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: tap-jenkins-app-workload
  namespace: mydev-ns
spec:
  params:  #! Required: selects the pipeline
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: jenkins-pipeline
  #! Required: Passes parameters to pipeline
  - name: testing_pipeline_params
    value:
      #! Required: Name of the Jenkins job
      job-name: tap-jenkins-pipeline
      secret-name: jenkins-secret
      job-params: "[{\"name\":\"GIT_URL\", \"value\":\"https://github.com/dkhopade/tap-jenkins-app/\"}, {\"name\":\"GIT_BRANCH\", \"value\":\"master\"}]"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/dkhopade/tap-jenkins-app